FROM amazonlinux:${version} as dev
RUN yum -y groupinstall "Development Tools"

FROM dev as go

ENV GOPATH /root/.go
ENV GOROOT /usr/local/go
ENV PATH "/usr/local/go/bin:${PATH}"
ENV PATH "/root/.go/bin:${PATH}"

RUN \
  curl https://storage.googleapis.com/golang/go1.15.1.linux-amd64.tar.gz -o go.tar.gz && \
  tar -xzf go.tar.gz && \
  mv go /usr/local && \
  rm -rf go.tar.gz && \
  go get github.com/tj/node-prune

FROM amazonlinux:${version}

LABEL maintainer="James Kyburz james.kyburz@gmail.com"

ARG NODE_VERSIONS
RUN test -n "$NODE_VERSIONS"

ENV PATH "/root/.go/bin:${PATH}"
ENV PATH "/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:${PATH}"

ENV NPM_CONFIG_LOGLEVEL warn

COPY --from=go /root/.go/bin /root/.go/bin

RUN \
  yum install -y git git-core tar gcc-c++ make zip && \
  bash -c $'\n\
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash\n\
  . /root/.nvm/nvm.sh\n\
  for node_version in ${NODE_VERSIONS:?}; do\n\
    nvm install ${node_version:?}\n\
  done\n\
  curl -o- -L https://yarnpkg.com/install.sh | bash\n\
  /root/.yarn/bin/yarn global add npm@latest npx@latest\n\
  for node_version in ${NODE_VERSIONS:?}; do\n\
    nvm use ${node_version:?}\n\
    npm install npm@latest -g\n\
    npm config set audit false\n\
  done\n\
  '
